image: elixir:latest

variables:
  MIX_ENV: test

stages:
  - setup
  - build
  - test

before_script:
  - make init

get-dependencies:
  stage: setup
  script:
    - make deps
  artifacts:
    expire_in: 30 minutes
    paths:
      - deps
      - mix.lock

compile:
  stage: build
  script:
    - make compile

lint:
  stage: test
  script:
    - make lint

tests:
  stage: test
  script:
    - make test
    - mix coveralls.json
  coverage: /\[TOTAL\]\s+(\d+\.\d+)%/
