language: elixir

elixir:
  - 1.3
  - 1.4
  - 1.5

otp_release:
  - 18
  - 19
  - 20

env:
  - MIX_ENV=test

script:
  - mix deps.get
  - mix credo --strict
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
