language: elixir

elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.1

otp_release:
  - 18.3
  - 19.3
  - 20.0

matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 20.0

env:
  - MIX_ENV=test

script:
  - mix deps.get
  - mix credo --strict
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
