language: elixir

elixir:
  - 1.3.2
  - 1.4.2
  - 1.5

otp_release:
  - 18.2
  - 19
  - 20

env:
  - MIX_ENV=test

script:
  - mix deps.get
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
