language: elixir

elixir:
  - 1.3.2
  - 1.4.2

otp_release:
  - 18.2

env:
  - MIX_ENV=test

script:
  - mix deps.get
  - mix coveralls.json
  - MIX_ENV=dev mix dialyzer

after_success:
  - bash <(curl -s https://codecov.io/bash)
